api_platform:
    title: Volley Club API
    version: 1.0.0
    defaults:
        pagination_enabled: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        formats:
            jsonld: ['application/ld+json']
            json: ['application/json']